export enum CacheTags {
  HN_POSTS = "HN_POSTS",
  HN_PINNED = "HN_PINNED",

  CMS_STACKS = "CMS_STACKS",
  CMS_PRODUCTS = "CMS_PRODUCTS",
  CMS_PROFILE = "CMS_PROFILE",
  CMS_WORKS = "CMS_WORKS",
  CMS_PAGES = "CMS_PAGES",
}
